### ISSUE TITLE
dragging a mutator block activates the mutator edit flyout

### ISSUE THREAD

**Issue by yoderjen** [RaspberryPiFoundation/blockly#145]
If user tries to grab a block and drag it around when the cursor happens to be over the mutator icon, the block is both dragged AND the mutator edit window is activated.  

Preferred behavior would be that if the mouse is dragged, don't count it as a click on the mutator icon.

**Comment by yoderjen** [comment]
This is easy to fix, in case anyone is looking.  in mutator.js, in the function iconClick_(), adding this code at the beginning fixes the problem:

  if (Blockly.dragMode_ == 2) {
    // Drag operation is concluding.  Don't open the editor.
    return;
  }

**Comment by NeilFraser** [comment]
Good solution (though I moved it to icon.js so that it applies to comments and warnings too).
