### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by Immortalin** [RaspberryPiFoundation/blockly#156]
According to [here](https://developers.google.com/blockly/hacking/mistakes?hl=en), material design is not used due to the fact that it's harder to distinguish borders but can a more modern design be used? I.e. flatter blocks but retaining the original color.

**Comment by NeilFraser** [comment]
The issue raised in that page is not the colours.  It is the removal of the edges, which makes it impossible to see where one block ends and another begins.  Remove the 1-pixel highlight on the left and top edges, and the 1-pixel shadow on the right and bottom edges and you'll have a problem.  Regardless of the choice of colours.

If the blocks are flat, how does one distinguish between two blocks of the same colour that are connected?
