### ISSUE TITLE
Comment bubble won't appear in IE 11

### ISSUE THREAD

**Issue by yoderjen** [RaspberryPiFoundation/blockly#157]
I can add the comment icon, but when clicking the icon nothing happens.  

The developers console throws the error: Object doesn't support property or method 'getAllText'

from this code: Blockly.Warning.textToDom_(this.getAllText());  (out of warning.js)

using IE 11.0.9600.17959

**Comment by carlosperate** [comment]
This was caused due to the comment object delegating, only in IE, the bubble creation to the warning object: https://github.com/google/blockly/blob/master/core/comment.js#L137-L144
The submitted pull request should solve this.

**Comment by yoderjen** [comment]
Thank you, although since the comment is uneditable, it is less useful than I'd hoped.  I wonder if a FieldTextInput style editor could be used in the bubble so that IE could have functional comments.
